[build]
  publish = "gabrieljones/public"
  command = "cd gabrieljones && hugo --themesDir ../.."

[build.environment]
  HUGO_VERSION = "0.83.1"
  HUGO_THEME = "repo"
  HUGO_BASEURL = "https://dynamic-gingersnap-d26d6a.netlify.app/"

[[headers]]
  for = "/*"
    [headers.values]
      Access-Control-Allow-Origin = "*"
