name = "Gabriel Jones"
license = "MIT"
licenselink = "/"
description = "Si dice che mi piaccia la grafica, è vero."
homepage = ""
tags = ["accessible", "blog", "documentation", "dark"]
features = ["accessible", "blog", "documentation", "dark"]
min_version = "0.81.0"

[author]
  name = "Zachary Betz"
  homepage = "https://zwbetz.com/"

[original]
  name = "Cupper"
  homepage = "https://thepaciellogroup.github.io/cupper/"
  repo = "https://github.com/ThePacielloGroup/cupper"